//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBDS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Baidang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Baidang()
        {
            this.PhanCongSales = new HashSet<PhanCongSale>();
            this.Sales = new HashSet<Sale>();
        }
    
        public int idbaidang { get; set; }
        public string tenbaidang { get; set; }
        public Nullable<int> diachi { get; set; }
        public Nullable<decimal> gia { get; set; }
        public Nullable<int> dientich { get; set; }
        public Nullable<int> loaibaidang { get; set; }
        public string mota { get; set; }
        public byte[] image { get; set; }
        [Display(Name="Hình ảnh")]
        public string urlimage { get; set; }
        public Nullable<int> trangthai { get; set; }
        public Nullable<System.DateTime> ngaydang { get; set; }
        public Nullable<System.DateTime> ngaycapnhat { get; set; }
    
        public virtual QuanHuyen QuanHuyen { get; set; }
        public virtual LoaiBaiDang LoaiBaiDang1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanCongSale> PhanCongSales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
