//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBDS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_BatDongSan : DbContext
    {
        public DB_BatDongSan()
            : base("name=DB_BatDongSan")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<BatDongSan> BatDongSans { get; set; }
        public virtual DbSet<CauHoi> CauHois { get; set; }
        public virtual DbSet<DIEM> DIEMs { get; set; }
        public virtual DbSet<DonVi> DonVis { get; set; }
        public virtual DbSet<DuAn> DuAns { get; set; }
        public virtual DbSet<LoaiBaiDang> LoaiBaiDangs { get; set; }
        public virtual DbSet<LoaiDuAn> LoaiDuAns { get; set; }
        public virtual DbSet<LoaiNhaDat> LoaiNhaDats { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhanCong> PhanCongs { get; set; }
        public virtual DbSet<PhiHoaHong> PhiHoaHongs { get; set; }
        public virtual DbSet<PhuongXa> PhuongXas { get; set; }
        public virtual DbSet<QuanHuyen> QuanHuyens { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<TinhThanhPho> TinhThanhPhoes { get; set; }
        public virtual DbSet<TraLoi> TraLois { get; set; }
    }
}
