//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBDS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BATDONGSANEntities1 : DbContext
    {
        public BATDONGSANEntities1()
            : base("name=BATDONGSANEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Baidang> Baidangs { get; set; }
        public virtual DbSet<LoaiBaiDang> LoaiBaiDangs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhanCongSale> PhanCongSales { get; set; }
        public virtual DbSet<PhiHoaHong> PhiHoaHongs { get; set; }
        public virtual DbSet<PhongBan> PhongBans { get; set; }
        public virtual DbSet<QuanHuyen> QuanHuyens { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<TinhThanhPho> TinhThanhPhoes { get; set; }
    }
}
