//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBDS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DuAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DuAn()
        {
            this.BatDongSans = new HashSet<BatDongSan>();
        }

        public int ID { get; set; }
        [Required(ErrorMessage = "Bạn cần nhập tên dự án")]
        public string TenDuAn { get; set; }
        [Required(ErrorMessage = "Bạn cần chọn quận huyện")]
        public int IDQuanHuyen { get; set; }
        public Nullable<int> IDPhuongXa { get; set; }
        [Required(ErrorMessage = "Bạn cần chọn tỉnh thành")]
        public int IDTinhThanhPho { get; set; }
        [Required(ErrorMessage = "Bạn cần nhập địa chỉ")]
        public string DiaChi { get; set; }
        public string DonViPhanPhoi { get; set; }
        public Nullable<double> TongDienTich { get; set; }
        public Nullable<double> GiaBan { get; set; }
        [Required(ErrorMessage = "Bạn cần chọn loại dự án")]
        public int IDLoaiDuAn { get; set; }
        [Required(ErrorMessage = "Bạn cần nhập mô tả")]
        public string MoTa { get; set; }
        public string Urlimage { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public System.DateTime NgayDang { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
        public string ChuDauTu { get; set; }
        public string QuyMoDuAn { get; set; }
        public string MatDoXayDung { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatDongSan> BatDongSans { get; set; }
        public virtual LoaiDuAn LoaiDuAn { get; set; }
        public virtual PhuongXa PhuongXa { get; set; }
        public virtual QuanHuyen QuanHuyen { get; set; }
        public virtual TinhThanhPho TinhThanhPho { get; set; }
    }
}
