//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanCong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhanCong()
        {
            this.PhiHoaHongs = new HashSet<PhiHoaHong>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDBatDongSan { get; set; }
        public Nullable<int> IDSales { get; set; }
        public Nullable<double> PhanTramHoaHong { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual BatDongSan BatDongSan { get; set; }
        public virtual Sale Sale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhiHoaHong> PhiHoaHongs { get; set; }
    }
}
