//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanCongSale
    {
        public int idphancong { get; set; }
        public Nullable<int> baidang { get; set; }
        public Nullable<int> nhanvien { get; set; }
        public Nullable<int> sales { get; set; }
        public Nullable<double> phantramhoahong { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
    
        public virtual Baidang Baidang1 { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
