//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhiHoaHong
    {
        public int ID { get; set; }
        public Nullable<double> TongTien { get; set; }
        public Nullable<int> IDSales { get; set; }
        public Nullable<int> IDPhanCong { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
    
        public virtual PhanCong PhanCong { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
