//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBDS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhiHoaHong
    {
        public int idhoahong { get; set; }
        public Nullable<int> sale { get; set; }
        public Nullable<decimal> tongtien { get; set; }
        public Nullable<int> nguoitao { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual Sale Sale1 { get; set; }
    }
}
