//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBDS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.DIEMs = new HashSet<DIEM>();
            this.PhanCongs = new HashSet<PhanCong>();
            this.PhiHoaHongs = new HashSet<PhiHoaHong>();
        }

        public int ID { get; set; }
        [Required(ErrorMessage = "Bạn cần nhập tên Sale")]
        public string TenSales { get; set; }
        [Required(ErrorMessage = "Bạn cần nhập Email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Bạn cần nhập số điện thoại")]
        public string SoDienThoai { get; set; }
        [Required(ErrorMessage = "Bạn cần nhập địa chỉ")]
        public string DiaChi { get; set; }
        [Required(ErrorMessage = "Bạn cần nhập tài khoản")]
        public string TaiKhoan { get; set; }
        [Required(ErrorMessage = "Bạn cần nhập mật khẩu")]
        public string MatKhau { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<int> ChoKiemTra { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIEM> DIEMs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhanCong> PhanCongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhiHoaHong> PhiHoaHongs { get; set; }
    }
}
